/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "selverf adapter settings": {                     "en": "Adapter settings for SelveRF",                     "de": "Adaptereinstellungen für selverf",                 "ru": "Настройки адаптера для selverf",                   "pt": "Configurações do adaptador para selverf",          "nl": "Adapterinstellingen voor selverf",                 "fr": "Paramètres d'adaptateur pour selverf",             "it": "Impostazioni dell'adattatore per selverf",         "es": "Ajustes del adaptador para selverf",               "pl": "Ustawienia adaptera dla selverf",                  "uk": "Налаштування адаптера для selverf",                "zh-cn": "selverf的适配器设置"},
    "usbGatewayPath": {                               "en": "Path to the USB Gateway",                          "de": "Pfad zum USB-Gateway",                             "ru": "Путь к USB-шлюзу",                                 "pt": "Caminho para o gateway USB",                       "nl": "Pad naar de USB-gateway",                          "fr": "Chemin d'accès à la passerelle USB",               "it": "Percorso del gateway USB",                         "es": "Ruta a la puerta de enlace USB",                   "pl": "Ścieżka do bramy USB",                             "uk": "Шлях до USB-шлюзу",                                "zh-cn": "USB 网关的路径"},
};